# Конфигурация markdownlint
default: true

# Длина строки - отключаем для фрагментов кода
MD013:  # проверка длины строки
  line_length: 88

# Повторяющиеся заголовки - нормально для структуры docs/
# MD024: false

# Несколько H1 в одном файле - иногда нужно
# MD025: false

# Inline HTML - иногда необходим
# MD033: false
