# Конфигурация markdownlint
default: true

# Длина строки - отключаем для фрагментов кода
# MD013: false

# Повторяющиеся заголовки - нормально для структуры docs/
# MD024: false

# Несколько H1 в одном файле - иногда нужно
# MD025: false

# Inline HTML - иногда необходим
# MD033: false
